#!/bin/sh
# $Id: gauge0-input-fd,v 1.1 2003/10/09 22:16:46 tom Exp $
# modified "gauge0" script to use "--input-fd" option.
: ${DIALOG=dialog}

exec 3<&0
PCT=10
(
sleep 1
while test $PCT != 110
do
echo "XXX"
echo $PCT
echo "The new\n\
message ($PCT percent)"
echo "XXX"
PCT=`expr $PCT + 10`
sleep 1
done
) |

$DIALOG --title "GAUGE" --input-fd 3 --gauge "Hi, this is a gauge widget" 0 0 0

exec 3<&-
