#!/bin/sh
# $Id: pause,v 1.4 2010/01/13 10:20:03 tom Exp $

. ./setup-vars

$DIALOG --title "PAUSE" "$@" --pause "Hi, this is a pause widget" 20 70 10

retval=$?

case $retval in
  0)
    echo "Timeout expired.";;
  1)
    echo "Cancel pressed.";;
  *)
    echo "Unexpected return code: $retval";;
esac
