#! /bin/sh
# $Id: yesno-utf8,v 1.6 2010/01/13 10:20:03 tom Exp $

. ./setup-vars

. ./setup-utf8

DIALOG_ERROR=254
export DIALOG_ERROR

$DIALOG "$@" --yesno "Are you a ＤＯＧ?" 0 0
retval=$?

. ./report-button
