#! /bin/sh
# $Id: yesno-utf8,v 1.1 2009/02/22 17:48:24 tom Exp $
: ${DIALOG=dialog}

case none"$LANG$LC_ALL$LC_CTYPE" in
*UTF-8*)
	;;
*)
	echo "This script must be run in a UTF-8 locale"
	exit 1
	;;
esac

DIALOG_ERROR=254
export DIALOG_ERROR

$DIALOG --yesno "Are you a ＤＯＧ?" 0 0

case $? in
  0)
    echo "OK"
    ;;
  1)
    echo "Button 1 (Cancel) pressed";;
  2)
    echo "Button 2 (Help) pressed";;
  3)
    echo "Button 3 (Extra) pressed";;
  254)
    echo "ERROR!";;
  255)
    echo "ESC pressed.";;
esac
